"""Typed, persistent action-observation runtime for RepoPilot agents."""

from .approval import (
    APPROVAL_PROTOCOL_VERSION,
    DEFAULT_APPROVAL_TTL_SECONDS,
    MAX_APPROVAL_TTL_SECONDS,
    RuntimeApprovalGrant,
    RuntimeApprovalRequest,
    approval_payload_hash,
)
from .loop import AgentRuntime
from .models import (
    READ_ONLY_ACTIONS,
    SIDE_EFFECT_ACTIONS,
    STOPPING_OBSERVATION_STATUSES,
    SUPPORTED_ACTIONS,
    RuntimeAction,
    RuntimeEvent,
    RuntimeObservation,
    RuntimePolicy,
    RuntimeRunResult,
)
from .store import InMemoryRuntimeStore, RuntimeEventStore, SQLiteRuntimeStore
from .state import (
    AGENT_WORKING_STATE_VERSION,
    MAX_RECENT_OBSERVATIONS,
    AgentAcceptanceState,
    AgentPlanItem,
    AgentProposedEditState,
    AgentStateObservation,
    AgentWorkingState,
    advance_agent_working_state,
    agent_completion_blockers,
    agent_completion_ready,
    agent_working_state_from_record,
    apply_agent_state_update,
    create_agent_working_state,
    latest_agent_working_state,
    render_agent_working_state,
    stop_agent_working_state,
)

__all__ = [
    "AgentRuntime",
    "AgentAcceptanceState",
    "AgentPlanItem",
    "AgentProposedEditState",
    "AgentStateObservation",
    "AgentWorkingState",
    "AGENT_WORKING_STATE_VERSION",
    "APPROVAL_PROTOCOL_VERSION",
    "DEFAULT_APPROVAL_TTL_SECONDS",
    "InMemoryRuntimeStore",
    "MAX_APPROVAL_TTL_SECONDS",
    "MAX_RECENT_OBSERVATIONS",
    "READ_ONLY_ACTIONS",
    "RuntimeAction",
    "RuntimeApprovalGrant",
    "RuntimeApprovalRequest",
    "RuntimeEvent",
    "RuntimeEventStore",
    "RuntimeObservation",
    "RuntimePolicy",
    "RuntimeRunResult",
    "SIDE_EFFECT_ACTIONS",
    "STOPPING_OBSERVATION_STATUSES",
    "SQLiteRuntimeStore",
    "SUPPORTED_ACTIONS",
    "advance_agent_working_state",
    "approval_payload_hash",
    "agent_completion_blockers",
    "agent_completion_ready",
    "agent_working_state_from_record",
    "apply_agent_state_update",
    "create_agent_working_state",
    "latest_agent_working_state",
    "render_agent_working_state",
    "stop_agent_working_state",
]
